package pluse;

import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import project.Sortie;
public class print extends javax.swing.JFrame {

	JFrame frame;


	/**
	 * Launch the application.
	 */


	/**
	 * Create the application.
	 */


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
print(){initComponents();}



/**
 *
 * @author USER
 */

    /**
     * Creates new form print
     */
    public print(ResultSet Rs) throws SQLException {
        initComponents();
      /*  jTextArea1.setText("\t \t  «·Ã„ÂÊ—Ì‹‹‹‹‹… «·Ã“«∆—Ì‹‹‹… «·œÌ„ﬁ—«ÿÌ‹‹‹… «·‘⁄»Ì‹‹‹‹‹‹… \n \n"+
          "\t \t caise nationale des retraits\n \n"+
          "\t \t agence tiaret  \n \n"+
          "\t \t service d'archive \t \n \n \n \n "+
          
          "\t\t\t\t "+Rs.getString(1)+"  \t \n \n  "+
          "\t\t \t\t "+Rs.getString(2)+" \t \n \n "+
          "\t\t \t\t "+Rs.getString(3)+" \t \n \n"+
          "\t\t \t\t  "+Rs.getString(4)+ " \t \n \n \n"+
          "\t\t \t\t  "+Rs.getString(5)+" \n \n \n \n"+
          "                          \t \t          ");*/
                                                         
    	String msg="\t\t\t\t  BON DE SORTEE \n  date: "+"21/12/2017"+"\t\t\t"
				+ " Service de :"+"secÈritÈ"+"";
    	
    	
        jTextArea1.setText("\t \t  «·Ã„ÂÊ—Ì‹‹‹‹‹… «·Ã“«∆—Ì‹‹‹… «·œÌ„ﬁ—«ÿÌ‹‹‹… «·‘⁄»Ì‹‹‹‹‹‹… \n \n"+
                "\t \t caise nationale des retraits\n \n"+
                "\t \t agence tiaret  \n \n"+
                "\t \t service d'archive \t \n \n \n \n "+
             msg
           
              );
        


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
      new JFrame();
  setResizable(false);
   setBounds(100, 100, 833, 662);
	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		getContentPane();
		setVisible(true);
    	
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ÿ»⁄");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(282)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(35)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 711, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(39)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1.setViewportView(jTextArea1);
        
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            Boolean a = jTextArea1.print();
            if(a){
                JOptionPane.showMessageDialog(null, "impression en cours");
            }else{
                JOptionPane.showMessageDialog(null, "annulation de l'impression");
            }
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(print.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
   
        
  /*	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
    	
     	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

				try {
			new print();
	
				} catch (Exception e) {
					e.printStackTrace();
				}
			
            }
        });  
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}

